<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>2</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>29</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>0.0</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>1006.3222239182259</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>250.0</KnownMass>
                    <Density>1200.0</Density>
                    <Material>Polycarbonate (Lexan)</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>157.80983476006614</CalcMass>
                    <CalcCG>201.3090054538434</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>253.99999999999994</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>237.00000000000003</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>10.000000000000036</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>10.000000000000036</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>15.799999999999967</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>78.74000000000001</BaseDia>
                    <ShoulderLen>25.4</ShoulderLen>
                    <ShoulderOD>76.19999999999999</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>45.400000000000006</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>38.70506360800369</CalcMass>
                    <CalcCG>92.07499999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>184.14999999999998</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>3</SerialNo>
                    <OD>78.74000000000001</OD>
                    <ID>76.19999999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>76.19999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>71.00000000000001</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>147.31999999999996</Xb>
                            <CalcMass>62.5499980497115</CalcMass>
                            <CalcCG>2.54</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.08</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>76.19999999999999</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>110.0</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-86.35999999999999</Xb>
                            <CalcMass>62.13369306269177</CalcMass>
                            <CalcCG>2.54</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.08</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>75.946</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>32.6</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-81.28</Xb>
                            <CalcMass>25.648643117606568</CalcMass>
                            <CalcCG>52.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>105.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>75.946</OD>
                            <ID>72.87259999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>632.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Upper Rec/AV Bay</Name>
                            <KnownCG>304.59</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>304.59</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>215.89999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>272.0</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Sustainer Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>262.19147034347384</CalcMass>
                    <CalcCG>393.7</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>787.4</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>8</SerialNo>
                    <OD>78.74000000000001</OD>
                    <ID>74.676</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>74.676</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>226.7</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>56.87292725035662</CalcMass>
                            <CalcCG>158.75</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>317.5</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>57.400000000000006</OD>
                            <ID>54.400000000000006</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>54.400000000000006</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>80.8</KnownMass>
                                    <Density>630.0</Density>
                                    <Material>Plywood (birch)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>210.0</Xb>
                                    <CalcMass>9.047755281113409</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>10</SerialNo>
                                    <OD>76.2</OD>
                                    <ID>54.1</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>80.8</KnownMass>
                                    <Density>630.0</Density>
                                    <Material>Plywood (birch)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>70.0</Xb>
                                    <CalcMass>9.047755281113409</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>11</SerialNo>
                                    <OD>76.2</OD>
                                    <ID>54.1</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <MassObject>
                            <KnownMass>80.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>424.17999999999995</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>424.17999999999995</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>262.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>139.7</Xb>
                            <CalcMass>47.23842382499392</CalcMass>
                            <CalcCG>139.49999999999997</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>278.99999999999994</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <FinSet>
                            <KnownMass>143.74587002768496</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>50.79999999999998</Xb>
                            <CalcMass>143.74587002768496</CalcMass>
                            <CalcCG>144.3102526949575</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>14</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>199.99959999999996</RootChord>
                            <TipChord>35.0012</TipChord>
                            <SemiSpan>75.00619999999999</SemiSpan>
                            <SweepDistance>199.32396</SweepDistance>
                            <Thickness>6.35</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>133.65000000000003</TabLength>
                            <TabDepth>1.2700000000000071</TabDepth>
                            <TabOffset>55.09979999999981</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts>
                <BodyTube>
                    <KnownMass>68.0</KnownMass>
                    <Density>1300.0</Density>
                    <Material>Blue tube</Material>
                    <Name>Body tube - Interstage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>71.44342369834342</CalcMass>
                    <CalcCG>88.89999999999998</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>177.79999999999995</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>15</SerialNo>
                    <OD>78.74000000000001</OD>
                    <ID>76.19999999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>76.19999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>64.13566784852094</KnownMass>
                            <Density>1300.0</Density>
                            <Material>Blue tube</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-63.5</Xb>
                            <CalcMass>64.13566784852094</CalcMass>
                            <CalcCG>68.6689</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>137.3378</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>75.946</OD>
                            <ID>72.87259999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>69.98343634293946</KnownMass>
                            <Density>1300.0</Density>
                            <Material>Blue tube</Material>
                            <Name>Upper - Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>1190.4899999999998</Xb>
                            <CalcMass>69.98343634293946</CalcMass>
                            <CalcCG>74.92999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>149.85999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>75.946</OD>
                            <ID>72.87259999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>71.00000000000001</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>1324.61</Xb>
                            <CalcMass>62.5499980497115</CalcMass>
                            <CalcCG>2.54</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>5.08</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>76.19999999999999</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>350.9</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Lower Rec/AV Bay</Name>
                            <KnownCG>1319.5122</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>1319.5122</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>19</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>71.00000000000001</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>1466.85</Xb>
                            <CalcMass>62.5499980497115</CalcMass>
                            <CalcCG>2.54</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>5.08</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <OD>76.19999999999999</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>241.09141855459006</KnownMass>
                    <Density>1300.0</Density>
                    <Material>Blue tube</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>241.09141855459006</CalcMass>
                    <CalcCG>300.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>600.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>21</SerialNo>
                    <OD>78.74000000000001</OD>
                    <ID>76.19999999999999</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>76.19999999999999</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>46.17026304836261</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>46.17026304836261</CalcMass>
                            <CalcCG>130.81</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>261.62</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <OD>76.19999999999999</OD>
                            <ID>74.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>74.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>62.5499980497115</KnownMass>
                                    <Density>2700.0</Density>
                                    <Material>Aluminum</Material>
                                    <Name>Engine block</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>231.14</Xb>
                                    <CalcMass>62.5499980497115</CalcMass>
                                    <CalcCG>2.54</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>5.08</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>23</SerialNo>
                                    <OD>76.19999999999999</OD>
                                    <ID>0.0</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>5.0</KnownMass>
                                    <Density>630.0</Density>
                                    <Material>Plywood (birch)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>20.0</Xb>
                                    <CalcMass>9.047755281113409</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>24</SerialNo>
                                    <OD>76.2</OD>
                                    <ID>54.1</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>5.0</KnownMass>
                                    <Density>630.0</Density>
                                    <Material>Plywood (birch)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>195.0</Xb>
                                    <CalcMass>9.047755281113409</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>25</SerialNo>
                                    <OD>76.2</OD>
                                    <ID>54.1</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>78.18749756213937</KnownMass>
                                    <Density>2700.0</Density>
                                    <Material>Aluminum</Material>
                                    <Name>Bulkhead</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>261.62</Xb>
                                    <CalcMass>78.18749756213937</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>26</SerialNo>
                                    <OD>76.19999999999999</OD>
                                    <ID>0.0</ID>
                                    <UsageCode>1</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <FinSet>
                            <KnownMass>337.88221133099995</KnownMass>
                            <Density>1050.0</Density>
                            <Material>Polystyrene</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>337.88221133099995</CalcMass>
                            <CalcCG>138.99468329791316</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>27</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>228.6</RootChord>
                            <TipChord>101.6</TipChord>
                            <SemiSpan>76.19999999999999</SemiSpan>
                            <SweepDistance>120.98374890868602</SweepDistance>
                            <Thickness>6.35</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>168.65000000000003</TabLength>
                            <TabDepth>1.2700000000000071</TabDepth>
                            <TabOffset>33.600000000000016</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <MassObject>
                            <KnownMass>70.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>304.79999999999995</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>304.79999999999995</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>200.0</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>96.52</Xb>
                            <CalcMass>22.79485503333063</CalcMass>
                            <CalcCG>101.59999999999997</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.19999999999993</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>29</SerialNo>
                            <Dia>609.5999999999999</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
            </Stage2Parts>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>